# Path to Deadlock root folder
deadlock_path = 'C:/Program Files (x86)/Steam/steamapps/common/Deadlock'

# Path to decompiled `heroes.vdata` file
heroes_vdata_path = './heroes.vdata'

# Path to decompiled `abilities.vdata` file
abilities_vdata_path = './abilities.vdata'

# Output path for generated files
output_path = './modded/'

# Textual theme. Can be changed at runtime via the Command Palette (Ctrl+P)
theme = "tokyo-night"
